

server:
  port: 8085
 
spring:
  application:
    name: api-gateway
    

zuul:
  routes:
    api-gateway-with-eureka:
      path: /api/with-eureka/**
      service-id: FIRSTEUREKACLIENT     #This is the Service Id of the micro-service registered in Eureka
    api-gateway-without-eureka:
      path: /api/without-eureka/**
      url: http://localhost:8080/       #This is the URL of the micro-service


